import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale, getGT } from "gt-next/server";
import { GTProvider, LocaleSelector } from "gt-next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export async function generateMetadata(): Promise<Metadata> {
  const gt = await getGT();

  return {
    title: gt("Create Next App"),
    description: gt("Generated by create next app")
  };
}

export default async function RootLayout({
  children


}: Readonly<{children: React.ReactNode;}>) {
  return (
  <html lang={await getLocale()}>
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}><GTProvider>
        <div style={{ position: 'fixed', top: '1rem', right: '1rem', zIndex: 1000 }}>
          <LocaleSelector />
        </div>
        {children}
      </GTProvider></body>
    </html>
  );
}