import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale, getGT } from "gt-next/server";
import { GTProvider, LocaleSelector, T } from "gt-next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export async function generateMetadata(): Promise<Metadata> {
  const gt = await getGT();

  return {
    title: gt("Create Next App"),
    description: gt("Generated by create next app")
  };
}

export default async function RootLayout({
  children


}: Readonly<{children: React.ReactNode;}>) {
  return (
  <html lang={await getLocale()}>
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}><GTProvider>
        <header className="p-4 border-b border-gray-200 dark:border-gray-700">
          <div className="max-w-6xl mx-auto flex justify-between items-center">
            <div className="text-lg font-semibold">
              <T>My App</T>
            </div>
            <LocaleSelector />
          </div>
        </header>
        {children}
      </GTProvider></body>
    </html>
  );
}